image:
  repository: tccr.io/truecharts/jackett
  pullPolicy: IfNotPresent
  tag: 0.20.2122@sha256:81400068dda77978be5fce3513c1ff80978d50877e29b19b7f8494635362978e

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        protocol: HTTP
        targetPort: 9117
        port: 9117

probes:
  liveness:
    path: "/UI/Login"

  readiness:
    path: "/UI/Login"

  startup:
    path: "/UI/Login"

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
