image:
  repository: tccr.io/truecharts/tautulli
  pullPolicy: IfNotPresent
  tag: 2.10.4@sha256:706349ed146da1229c861f66eba795752e0e867273646f54298fb3156f180bbc

service:
  main:
    ports:
      main:
        port: 8181
        targetPort: 8181

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
