env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/cloudbeaver
  tag: latest@sha256:3c5fb727b01da819b387dfce60b216fcab7f7d8fe56f942bf8943069a1808504
persistence:
  appdata:
    enabled: true
    mountPath: /opt/cloudbeaver/workspace
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8978
        protocol: TCP
        targetPort: 8978

portal:
  enabled: true
