env:
  GAME_PARAMS: ""
  GAME_PORT: "27016"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/longvinter
  tag: latest@sha256:78cc7ab2521e60e1a6cddc89c2f266ff97bb87a74bb41b9e6d4a9cdf138a9b43
persistence:
  serverfiles:
    enabled: true
    mountPath: /serverdata/serverfiles
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 27016
        protocol: UDP
        targetPort: 27016

portal:
  enabled: true
