apiVersion: v2
appVersion: "0.98.1"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 10.7.1
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.truecharts.org/
    version: 8.0.101
  - condition: redis.enabled
    name: redis
    repository: https://charts.truecharts.org
    version: 3.0.97
description: Turns any MySQL, PostgreSQL, SQL Server, SQLite & MariaDB into a smart-spreadsheet.
home: https://truecharts.org/docs/charts/stable/nocodb
icon: https://truecharts.org/img/hotlink-ok/chart-icons/nocodb.png
keywords:
  - nocodb
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: nocodb
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/nocodb
  - https://hub.docker.com/r/nocodb/nocodb
  - https://github.com/nocodb/nocodb
version: 3.0.53
annotations:
  truecharts.org/catagories: |
    - productivity
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
