image:
  repository: tccr.io/truecharts/storj-node
  tag: 1.65.1@sha256:64d8ec31f9295438814c7b21964ac52b5b5ab173b6f0185a56b0ae83413ef9d7
  pullPolicy: IfNotPresent

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

secretEnv:
  WALLET: "walletaddress"

env:
  SETUP: true
  EMAIL: ""
  ADDRESS: ""
  STORAGE: "500GB"

service:
  main:
    ports:
      main:
        port: 14002
        targetPort: 14002
  coretcp:
    enabled: true
    ports:
      coretcp:
        enabled: true
        protocol: TCP
        port: 28967
        targetPort: 28967
  coreudp:
    enabled: true
    ports:
      coreudp:
        enabled: true
        protocol: UDP
        port: 28967
        targetPort: 28967

persistence:
  identity:
    enabled: true
    mountPath: "/app/identity"
  storage:
    enabled: true
    mountPath: "/app/config"

portal:
  enabled: true
