image:
  repository: tccr.io/truecharts/homer
  tag: 22.10.1@sha256:01cdd13d9d713f0dbab7924be0c5897015ea66c624c5d3e547c3619e2d3189e4
  pullPolicy: IfNotPresent

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000

env:
  INIT_ASSETS: true

service:
  main:
    ports:
      main:
        port: 10178
        targetPort: 8080

persistence:
  config:
    enabled: true
    mountPath: "/www/assets"

portal:
  enabled: true
