env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/chronograf
  tag: latest@sha256:2fa244b000c2736bf145213a3cbf0eec2aebe71ce28ba78882f174d70b315e49
persistence:
  chronograf:
    enabled: true
    mountPath: /var/lib/chronograf
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8888
        protocol: TCP
        targetPort: 8888

portal:
  enabled: true
