apiVersion: v2
appVersion: "latest"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 10.7.1
description: This app runs a speedtest check every hour and graphs the results.
home: https://truecharts.org/docs/charts/incubator/speedtest-tracker
icon: https://truecharts.org/img/hotlink-ok/chart-icons/speedtest-tracker.png
keywords:
  - speedtest
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: speedtest-tracker
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/speedtest-tracker
  - https://github.com/henrywhitaker3/Speedtest-Tracker
version: 0.0.4
annotations:
  truecharts.org/catagories: |
    - speedtest
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
