image:
  repository: tccr.io/truecharts/qinglong
  pullPolicy: IfNotPresent
  tag: 2.14.7@sha256:91cedf1b0e9538041ea39041d0fd9354ce700fcbda4bc9ad6562ed229dfb6fe9

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 5700
        port: 10176

persistence:
  data:
    enabled: true
    mountPath: "/ql/data"

portal:
  enabled: true
