image:
  repository: tccr.io/truecharts/ddns-go
  pullPolicy: IfNotPresent
  tag: 4.2.0@sha256:d006e5d4348602943af5639663275858789ff15005dd8e86310a59a9e53d5815

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 9876
        port: 10168

persistence:
  data:
    enabled: true
    mountPath: "/root"

portal:
  enabled: true
