image:
  repository: tccr.io/truecharts/shlink
  pullPolicy: IfNotPresent
  tag: 3.3.2@sha256:99db1a2c49b8dae5852e6c0d24ad99b50313408706dd65ed9dde4ba966d68e48

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10153

probes:
  liveness:
    path: "/rest/health"
  readiness:
    path: "/rest/health"
  startup:
    path: "/rest/health"

env:
  DEFAULT_DOMAIN: ""
  GEOLITE_LICENSE_KEY: ""
  ANONYMIZE_REMOTE_ADDR: true
  ENABLE_PERIODIC_VISIT_LOCATE: true
  IS_HTTPS_ENABLED: true
  PORT: "{{ .Values.service.main.ports.main.port }}"
  DB_DRIVER: "postgres"
  DB_USER: "{{ .Values.postgresql.postgresqlUsername }}"
  DB_NAME: "{{ .Values.postgresql.postgresqlDatabase }}"
  DB_PASSWORD:
    secretKeyRef:
      name: dbcreds
      key: postgresql-password
  DB_HOST:
    secretKeyRef:
      name: dbcreds
      key: plainhost
  REDIS_SERVERS:
    secretKeyRef:
      name: rediscreds
      key: url

postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: shlink
  postgresqlDatabase: shlink

redis:
  enabled: true
  existingSecret: "rediscreds"
  redisUsername: "default"

portal:
  enabled: false
