image:
  repository: tccr.io/truecharts/picoshare
  tag: 1.2.1@sha256:7de54d466ff6c49f87031ce3055820df85ed93565637334e914a85019e9bac0e
  pullPolicy: IfNotPresent

secretEnv:
  PS_SHARED_SECRET: "somesecretcode"
  LITESTREAM_BUCKET: ""
  LITESTREAM_ENDPOINT: ""
  LITESTREAM_ACCESS_KEY_ID: ""
  LITESTREAM_SECRET_ACCESS_KEY: ""

env:
  PORT: "{{ .Values.service.main.ports.main.port }}"

service:
  main:
    ports:
      main:
        port: 10209

persistence:
  data:
    enabled: true
    mountPath: "/data"

portal:
  enabled: true
