env:
  VNC_PW: unraid
  VNC_RESOLUTION: 1360x768
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/blender-desktop-g3
  tag: latest@sha256:aa8025dac91122f5c9772eb14dc2ee480cc09acef8bf0a6d75f43ab55481b780
persistence:
  internalshare:
    enabled: true
    mountPath: /UNRAID_SHARE
  storageprojects:
    enabled: true
    mountPath: /srv/projects
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 6901
        protocol: HTTP
        targetPort: 6901
  webuivnc:
    enabled: true
    ports:
      webuivnc:
        enabled: true
        port: 5901
        protocol: TCP
        targetPort: 5901

portal:
  enabled: true
