image:
  repository: tccr.io/truecharts/overseerr
  tag: 1.30.1@sha256:97a4a458a8210437b980b44bc035f78d5fa01f56bddac211ef432cc01bc4ad8b
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false

env:
  LOG_LEVEL: info

service:
  main:
    ports:
      main:
        port: 5055
        targetPort: 5055

persistence:
  config:
    enabled: true
    mountPath: "/app/config"

portal:
  enabled: true
