apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: kavitaemail
version: 0.0.7
appVersion: "0.1.10"
description: Simple email relay server for kavita.
type: application
deprecated: false
home: https://truecharts.org/docs/charts/incubator/kavitaemail
icon: https://truecharts.org/img/hotlink-ok/chart-icons/kavitaemail.png
keywords:
  - kavitaemail
  - email
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/kavitaemail
  - https://truecharts.org/docs/charts/incubator/kavitaemail
  - https://github.com/Kareadita/KavitaEmail
  - https://hub.docker.com/r/kizaing/kavitaemail
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 10.7.1
    # condition:
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
annotations:
  truecharts.org/catagories: |
    - email
    - relay
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
