image:
  repository: tccr.io/truecharts/kavitaemail
  pullPolicy: IfNotPresent
  tag: 0.1.10@sha256:70c38a520e1b3cd6a3281dbf27903b2b21f7e088f2d474cbbcefa9c86050181e

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

secretEnv:
  SMTP_USER: ""
  SMTP_PASS: ""

env:
  DISP_NAME: kavita
  SMTP_HOST: ""
  SMTP_PORT: 587
  SEND_ADDR: ""

service:
  main:
    ports:
      main:
        protocol: HTTP
        port: 15003
        targetPort: 5003

persistence:
  config:
    enabled: false
    mountPath: /app/config

portal:
  enabled: false
