image:
  repository: tccr.io/truecharts/flaresolverr
  pullPolicy: IfNotPresent
  tag: 2.2.9@sha256:6938eee27a67395dd4c88f3b06697c7d0679812236a201cb6d21da4bdafc9245

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 8191
        targetPort: 8191

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
