env:
  ADD: shiny
  PASSWORD: yourpasswordhere
  ROOT: "FALSE"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/rstudio
  tag: latest@sha256:c02b7d6e0d1c6899c71a78f285c2e0dd4c28f542bd773587f95e27bf3266e822
persistence:
  userdatadirectory:
    enabled: true
    mountPath: /home/rstudio/Documents
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  hostport2:
    enabled: true
    ports:
      hostport2:
        enabled: true
        port: 3838
        protocol: TCP
        targetPort: 3838
  main:
    ports:
      main:
        port: 8787
        protocol: HTTP
        targetPort: 8787

portal:
  enabled: true
