image:
  repository: tccr.io/truecharts/xwiki
  tag: 14.8.0-postgres@sha256:a4fa7a4df2ec41ce763851c3ebc125db38cc4ee2f0dfa3c6564233337a2aeab1
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  DB_USER: "{{ .Values.postgresql.postgresqlUsername }}"
  DB_DATABASE: "{{ .Values.postgresql.postgresqlDatabase }}"
  # User Defined
  JAVA_OPTS: ""
  DB_HOST:
    secretKeyRef:
      name: dbcreds
      key: plainhost
  DB_PASSWORD:
    secretKeyRef:
      name: dbcreds
      key: postgresql-password

service:
  main:
    ports:
      main:
        port: 10208
        targetPort: 8080

persistence:
  config:
    enabled: true
    mountPath: "/usr/local/xwiki"

postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: xwiki
  postgresqlDatabase: xwiki

portal:
  enabled: true
