image:
  repository: tccr.io/truecharts/mosdns
  pullPolicy: IfNotPresent
  tag: 4.4.2@sha256:7064eb23a00f2e70509156daf8bf0164a9c9dcbc389cf7c9778aa8b93360f6dc

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 53
        port: 53
  dns-udp:
    enabled: true
    ports:
      dns-upd:
        enabled: true
        protocol: UDP
        targetPort: 53
        port: 53

persistence:
  data:
    enabled: true
    mountPath: "/etc/mosdns"

portal:
  enabled: false
