env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/ts-dnsserver
  tag: latest@sha256:818e4b12042abee55de96250d13457ac542a1bab238b2ef2dabb8599ea43eae5
persistence:
  config:
    enabled: true
    mountPath: /config
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  dnsport:
    enabled: true
    ports:
      dnsport:
        enabled: true
        port: 53
        protocol: UDP
        targetPort: 53
  main:
    ports:
      main:
        port: 5380
        protocol: HTTP
        targetPort: 5380

portal:
  enabled: true
