env:
  VNC_PW: unraid
  VNC_RESOLUTION: 1360x768
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/firefox-desktop-g3
  tag: latest@sha256:6a10e1ce98cde3dd1f87ece9262707d78a4c75af29d23e47548c850ee5729f61
persistence:
  internalshare:
    enabled: true
    mountPath: /UNRAID_SHARE
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 6901
        protocol: HTTP
        targetPort: 6901
  webuivnc:
    enabled: true
    ports:
      webuivnc:
        enabled: true
        port: 5901
        protocol: TCP
        targetPort: 5901

portal:
  enabled: true
