image:
  repository: tccr.io/truecharts/focalboard
  pullPolicy: IfNotPresent
  tag: 7.4.3@sha256:f0f860684c6d8232ca29d5fc0d0f8c197e59919ef62b7b5cc13e867526d61e4c

securityContext:
  readOnlyRootFilesystem: false

env: {}

focalboard:
  serverRoot: "http://localhost:10072"
  telemetry: false
  localOnly: false
  enableLocalMode: true

service:
  main:
    ports:
      main:
        port: 10072

persistence:
  uploads:
    enabled: true
    mountPath: "/uploads"

postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: focalboard
  postgresqlDatabase: focalboard

portal:
  enabled: true
