env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/pt-helper
  tag: latest@sha256:5e3b81cfc96d1bedd1f4f233e306868febb69d56c9e9b216bfd7919151e677fc
persistence:
  data:
    enabled: true
    mountPath: /data
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8192
        protocol: TCP
        targetPort: 8192

portal:
  enabled: true
