env:
  BEASTHOST: <BEASTHOST>
  LAT: xx.xxxxx
  LONG: xx.xxxxx
  MLATHOST: <MLATHOST>
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/tar1090
  tag: latest@sha256:b102643843b3f310e86ed67e1ed7e4b1731efad63db1b4723421234da69dabce
persistence: {}
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8078
        protocol: TCP
        targetPort: 80

portal:
  enabled: true
