apiVersion: v2
appVersion: "2.9.5"
description: This server allows you to sync any Joplin client
name: joplin-server
version: 8.1.4
kubeVersion: ">=1.16.0-0"
keywords:
  - joplin
  - notes
home: https://truecharts.org/docs/charts/stable/joplin-server
icon: https://truecharts.org/img/hotlink-ok/chart-icons/joplin-server.png
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/joplin-server
  - https://github.com/laurent22/joplin/tree/dev/packages/server
  - https://github.com/laurent22/joplin
  - https://hub.docker.com/r/joplin/server
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 10.7.1
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.truecharts.org/
    version: 8.0.101
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
