image:
  repository: tccr.io/truecharts/joplin-server
  tag: 2.9.5@sha256:33a4347d21a7824f7c4eab9ddeee60713f4d55a6f3707354b55b66bcec9266ba
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  APP_BASE_URL: http://localhost:22300
  APP_PORT: 22300
  DB_CLIENT: "pg"
  POSTGRES_DATABASE: "{{ .Values.postgresql.postgresqlDatabase }}"
  POSTGRES_USER: "{{ .Values.postgresql.postgresqlUsername }}"
  POSTGRES_PORT: "5432"
  POSTGRES_PASSWORD:
    secretKeyRef:
      name: dbcreds
      key: postgresql-password
  POSTGRES_HOST:
    secretKeyRef:
      name: dbcreds
      key: plainhost
  MAILER_ENABLED: 0
  MAILER_HOST: ""
  MAILER_PORT: 465
  MAILER_SECURE: true
  MAILER_AUTH_USER: ""
  MAILER_AUTH_PASSWORD: ""
  MAILER_NOREPLY_NAME: ""
  MAILER_NOREPLY_EMAIL: ""

probes:
  liveness:
    path: "/api/ping"
  readiness:
    path: "/api/ping"
  startup:
    path: "/api/ping"

service:
  main:
    ports:
      main:
        port: 22300
        targetPort: 22300

persistence:
  config:
    enabled: true
    mountPath: "/config"

postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: joplin
  postgresqlDatabase: joplin

portal:
  enabled: true
