env:
  NVIDIA_DRIVER_CAPABILITIES: all
  NVIDIA_VISIBLE_DEVICES: ""
  VNC_PASSWD: "123456"
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/obs-ndi
  tag: latest@sha256:df3f15713bb46320c6dc022e4c610f373e1cab00f1f5f15c5e32e4a7633c6d6d
persistence:
  configpath:
    enabled: true
    mountPath: /config/obs-studio
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 5901
        protocol: TCP
        targetPort: 5901

portal:
  enabled: true
