apiVersion: v2
appVersion: "1.1.1"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 10.7.1
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.truecharts.org/
    version: 8.0.101
description: A home for all your coupons and loyalty cards.
home: https://truecharts.org/docs/charts/incubator/coupon-store
icon: https://truecharts.org/img/hotlink-ok/chart-icons/coupon-store.png
keywords:
  - coupons
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: coupon-store
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/coupon-store
  - https://github.com/linuxserver/docker-airsonic
version: 0.0.3
annotations:
  truecharts.org/catagories: |
    - utilities
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
