env:
  APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE: "1"
  WINEARCH: win64
  WINEDEBUG: -all
  WINEPREFIX: /root/server
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/spaceengineers
  tag: latest@sha256:16a203c0a0d21ae7bd6d9ce37aeeb017f738b4540ba652b2a59c00b51a1cc1d9
persistence:
  savegame:
    enabled: true
    mountPath: /appdata/space-engineers/instances/Saves/
  serverconfig:
    enabled: true
    mountPath: /appdata/space-engineers/instances
  serverfiles:
    enabled: true
    mountPath: /appdata/space-engineers/SpaceEngineersDedicated
  steamcmd:
    enabled: true
    mountPath: /serverdata/steamcmd
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 27017
        protocol: UDP
        targetPort: 27017

portal:
  enabled: true
