image:
  repository: tccr.io/truecharts/minio-console
  tag: 0.21.0@sha256:015f386d5db6b7acb5e044de63d7ebda1e56afc5c65043655764108e9e7ebea2
  pullPolicy: IfNotPresent

args: ["server"]

secretEnv:
  CONSOLE_PBKDF_PASSPHRASE: "changeme"
  CONSOLE_PBKDF_SALT: "changeme"

env:
  CONSOLE_MINIO_SERVER: ""

service:
  main:
    ports:
      main:
        port: 9090
        targetPort: 9090

securityContext:
  readOnlyRootFilesystem: false

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
