image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/thunderbird
  tag: latest@sha256:d8280a1d9e46f8d603c7602988605df83bfe02d81049ae687f04157f6429bb22

podSecurityContext:
  runAsGroup: 0
  runAsUser: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

env:
  THUNDERBIRD_V: "latest"
  CUSTOM_RES_H: 768
  CUSTOM_RES_W: 1280
  DATA_PERM: 770
  THUNDERBIRD_LANG: "en-US"

service:
  main:
    ports:
      main:
        port: 10291
        targetPort: 8080

persistence:
  data:
    enabled: true
    mountPath: /thunderbird

portal:
  enabled: true
