image:
  repository: tccr.io/truecharts/fileflows
  tag: 1.0.5@sha256:d828ee0843ff0c9cb6c78efd484b8047e658d22cb936784c021532d209ffcc74
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10242
        targetPort: 5000

persistence:
  data:
    enabled: true
    mountPath: "/app/Data"
  logs:
    enabled: true
    mountPath: "/app/Logs"
  temp:
    enabled: true
    mountPath: "/temp"
  media:
    enabled: true
    mountPath: "/media"

portal:
  enabled: true
