image:
  repository: tccr.io/truecharts/audiobookshelf
  tag: 2.2.1@sha256:1eca4137fd26a32ec3bf623b64e384123a467412a973f4a4de0d3c3d7a6b082f
  pullPolicy: IfNotPresent

env:
  AUDIOBOOKSHELF_UID: "{{ .Values.security.PUID }}"
  AUDIOBOOKSHELF_GID: "{{ .Values.podSecurityContext.fsGroup }}"
  PORT: "{{ .Values.service.main.ports.main.port }}"
  TOKEN_SECRET:
    secretKeyRef:
      name: audiobookshelf-secrets
      key: TOKEN_SECRET

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

service:
  main:
    ports:
      main:
        port: 10223

probes:
  liveness:
    path: "/ping"
  readiness:
    path: "/ping"
  startup:
    path: "/ping"

persistence:
  config:
    enabled: true
    mountPath: "/config"
  audiobooks:
    enabled: true
    mountPath: "/audiobooks"
  metadata:
    enabled: true
    mountPath: "/metadata"

portal:
  enabled: true
