apiVersion: v2
appVersion: "0.4.18"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 10.7.1
description: A highly customizable homepage
home: https://truecharts.org/docs/charts/stable/homepage
icon: https://truecharts.org/img/hotlink-ok/chart-icons/homepage.png
keywords:
  - homepage
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: homepage
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/homepage
  - https://github.com/benphelps/homepage
version: 0.0.13
annotations:
  truecharts.org/catagories: |
    - dashboard
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
