env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/backuppc
  tag: latest@sha256:a4c4a6045de1229cca4bf1eed36efdc0d0809d5b92e6a26193fc7b81d058c805
persistence:
  backuplocation:
    enabled: true
    mountPath: /var/lib/backuppc
  configurationfiles:
    enabled: true
    mountPath: /etc/backuppc
  homedirectory:
    enabled: true
    mountPath: /home/backuppc
  logs:
    enabled: true
    mountPath: /www/logs
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8000
        protocol: TCP
        targetPort: 80

portal:
  enabled: true
