apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: redisinsight
version: 0.0.32
appVersion: "latest"
description: GUI for Redis.
type: application
deprecated: false
home: https://truecharts.org/docs/charts/incubator/redisinsight
icon: https://truecharts.org/img/hotlink-ok/chart-icons/redisinsight.png
keywords:
  - redisinsight
  - Tools-Utilities
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/redisinsight
  - https://redis.com/redis-enterprise/redis-insight/
  - https://hub.docker.com/r/redislabs/redisinsight
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 10.7.1
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
annotations:
  truecharts.org/catagories: |
    - Tools-Utilities
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
