env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/searx
  tag: latest@sha256:b0f86f74f8ddda4e3dc1e218bf291c5dff3094fe7f3c80189b1fe5d7dfc36212
persistence:
  config:
    enabled: true
    mountPath: /etc/searx
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8080
        protocol: TCP
        targetPort: 8080

portal:
  enabled: true
