image:
  repository: tccr.io/truecharts/sabnzbd
  pullPolicy: IfNotPresent
  tag: 3.6.1@sha256:8582acad84e944f2368dd3a8b56665aaece6c7d04e023ec38a49ec338dc708c1

env:
  HOST_WHITELIST_ENTRIES: ""

service:
  main:
    ports:
      main:
        port: 10097
        targetPort: 8080

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
