apiVersion: v2
appVersion: "1.16.0"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 10.7.1
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.truecharts.org/
    version: 8.0.101
description: Midarr is a minimal lightweight media server for enjoying your media
home: https://truecharts.org/docs/charts/incubator/midarr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/midarr.png
keywords:
  - midarr
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: midarr
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/midarr
  - https://github.com/midarrlabs/midarr-server
version: 0.0.5
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
