env:
  APP_BRANCH: ""
  BLACKLIST: ""
  DELAY: ""
  NOSEARCH: ""
  NOTIFICATIONS: ""
  RUNNOW: ""
  SKIPUPDATE: ""
  SORT: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/traktarr
  tag: latest@sha256:c3f2e4c967f7574d13b234c8cfa5d5bc25c007d891ecf8bf78e04f0654033785
persistence:
  config:
    enabled: true
    mountPath: /config
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

portal:
  enabled: false
