env: {}
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/farmos
  tag: latest@sha256:9bf914d8883849adc3044896a827aaa5ffe73beaa7c8b551fe9f1280f9da3db4
persistence:
  sitesdirectory:
    enabled: true
    mountPath: /var/www/html/sites
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 80
        protocol: TCP
        targetPort: 80

portal:
  enabled: true
