image:
  repository: tccr.io/truecharts/nextpvr
  tag: latest@sha256:77f52670594050fbd9964d6d6da758294d9be766b192e84ad1dc3501e3056e0d
  pullPolicy: IfNotPresent

env:
  HOST_IP: "localhost"

service:
  main:
    ports:
      main:
        port: 10183
        targetPort: 8866

persistence:
  config:
    enabled: true
    mountPath: "/config"
  recordings:
    enabled: true
    mountPath: "/recordings"
  buffer:
    enabled: true
    mountPath: "/buffer"

portal:
  enabled: true
