image:
  repository: tccr.io/truecharts/lazylibrarian
  pullPolicy: IfNotPresent
  tag: latest@sha256:c52d8116c6e03d7086e8a6c5e1e40508e6f4c41b0086070812d22406bb182d13

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 5299
        targetPort: 5299

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
