image:
  repository: tccr.io/truecharts/doplarr
  tag: 3.6.1@sha256:714059496b93b80a6a5af6ca636741ec385597dd52de867fbbd51c082f4ec9c0
  pullPolicy: IfNotPresent

secretEnv:
  OVERSEERR__API: ""
  OVERSEERR__DEFAULT_ID: ""
  SONARR__API: ""
  RADARR__API: ""
  DISCORD__ROLE_ID: ""
  DISCORD__TOKEN: ""

env:
  OVERSEERR__URL: ""
  DISCORD__MAX_RESULTS: 25
  DISCORD__REQUESTED_MSG_STYLE: ":plain"
  SONARR__URL: ""
  SONARR__QUALITY_PROFILE: ""
  SONARR__LANGUAGE_PROFILE: ""
  RADARR__URL: ""
  RADARR__QUALITY_PROFILE: ""
  PARTIAL_SEASONS: true
  LOG_LEVEL: ":info"

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

portal:
  enabled: false
