image:
  repository: tccr.io/truecharts/booksonic-air
  pullPolicy: IfNotPresent
  tag: v2201.1.0@sha256:d685be3dfe7d6921d04cd8f11952f6c84f9b3fe03f4e857e6a5e2aa1bf53589c

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10048
        targetPort: 4040

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
