image:
  repository: tccr.io/truecharts/ombi
  pullPolicy: IfNotPresent
  tag: 4.28.0@sha256:d49e5fd41b7cf1f6f8e46b698dc9e8bbddd2b1c8da0746c0e31667eef3406f7b

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        port: 3579
        targetPort: 3579

persistence:
  config:
    enabled: true
    mountPath: "/config"

# Enabled mariadb
# ... for more options see https://github.com/tccr.io/truecharts/charts/tree/master/tccr.io/truecharts/mariadb
mariadb:
  enabled: false
  architecture: standalone
  auth:
    database: ombi
    username: ombi
    password: ombi
  primary:
    persistence:
      enabled: false

portal:
  enabled: true
