image:
  repository: tccr.io/truecharts/autobrr
  pullPolicy: IfNotPresent
  tag: 1.8.1@sha256:8c4b755e5d44812c862eea9d24fb43e106c156998dab341615147c917605f037

service:
  main:
    ports:
      main:
        protocol: HTTP
        port: 7474
        targetPort: 7474

probes:
  liveness:
    enabled: true
    custom: true
    spec:
      exec:
        command:
          - /bin/sh
          - -c
          - curl --fail localhost:7474/
      failureThreshold: 5
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
  readiness:
    enabled: true
    custom: true
    spec:
      exec:
        command:
          - /bin/sh
          - -c
          - curl --fail localhost:7474/
      failureThreshold: 5
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
  startup:
    enabled: false

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
