env:
  UMASK: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/duplicacy
  tag: latest@sha256:b83294f973dc1303b1224ff64cadeaf6386759985be3ea0db4bd8b27ec06e91b
persistence:
  config:
    enabled: true
    mountPath: /config
  hostpathforcache:
    enabled: true
    mountPath: /cache
  hostpathforlogs:
    enabled: true
    mountPath: /logs
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 3875
        protocol: TCP
        targetPort: 3875

portal:
  enabled: true
