image:
  repository: tccr.io/truecharts/bookstack
  pullPolicy: IfNotPresent
  tag: 22.10.20221021@sha256:ca4e38ddf70130f039f709bbc581dc73cd1a126ead948181d3071176b0180696

env:
  DB_USER: "{{ .Values.mariadb.mariadbUsername }}"
  DB_DATABASE: "{{ .Values.mariadb.mariadbDatabase }}"
  APP_URL: ""
  DB_HOST:
    secretKeyRef:
      name: mariadbcreds
      key: plainhost
  DB_PASS:
    secretKeyRef:
      name: mariadbcreds
      key: mariadb-password
  APP_KEY:
    secretKeyRef:
      name: bookstack-secrets
      key: APP_KEY

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10112
        targetPort: 80

persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: "/config"

mariadb:
  enabled: true
  mariadbUsername: bookstack
  mariadbDatabase: bookstack
  existingSecret: "mariadbcreds"

portal:
  enabled: true
