env:
  TG_API_HASH: " "
  TG_API_ID: " "
  TG_AUTHORIZED_USER_ID: " "
  TG_BOT_TOKEN: ""
  TG_PROGRESS_DOWNLOAD: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/telethon-downloader
  tag: latest@sha256:7b5756c312feb04fabf57519af53f756ef25f701c5fb6652e2cc35f3d1fc6dc9
persistence:
  config:
    enabled: true
    mountPath: /config
  pathdownload:
    enabled: true
    mountPath: /download
  pathwatch:
    enabled: true
    mountPath: /watch
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

portal:
  enabled: false
