image:
  repository: tccr.io/truecharts/boinc
  pullPolicy: IfNotPresent
  tag: latest@sha256:58fce9e5828ea1bb84f074f1de14db42bb5f2966993a5d94eff1c6eaffad9366

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

# secretEnv:
#   PASSWORD: ""

service:
  main:
    ports:
      main:
        targetPort: 8080
        port: 10142

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

portal:
  enabled: true
