env:
  ADMINER_DESIGN: ""
  ADMINER_PLUGINS: ""
image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/adminer
  tag: latest@sha256:0a694102365a4fc61b72fb63a96004dbd97a359b9454e85f288913c2fbcb9003
persistence: {}
podSecurityContext:
  runAsGroup: 0
  runAsUser: 0
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
service:
  main:
    ports:
      main:
        port: 8080
        protocol: TCP
        targetPort: 8080

portal:
  enabled: true
